name: Push app to Heroku

on:
  push:
    branches:
      - master
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login 

          heroku container:push --app ${{ secrets.HEROKU_APP_NAME }} web 

          heroku container:release --app ${{ secrets.HEROKU_APP_NAME }} web 

          sleep 10
          
          heroku logs --app ${APP_NAME}
