name: Push app to Heroku

on:
  push:
    branches:
      - master
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache setup
        uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        
      - name: heroku build/deploy
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login 

          heroku container:push --app ${{ secrets.HEROKU_APP_NAME }} web 

          heroku container:release --app ${{ secrets.HEROKU_APP_NAME }} web 

          sleep 10
          
          heroku logs --app ${{ secrets.HEROKU_APP_NAME }}
